http5204-FirstMVC/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using http5204_FirstMVC.Models;
using http5204_FirstMVC.Models.ViewModels;
using System.Diagnostics;
using System.IO;

namespace http5204_FirstMVC.Controllers
{
    public class SearchController : Controller
    {

        //This is the controller which primarily deals with LIST
        private BlogCMSContext db = new BlogCMSContext();

        public ActionResult Explore()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Results(string searchkey)
        {
            //SearchItem is defined in Model/SearchItem.cs
            //SearchItems is referenced in Models/BlogCMSContext.cs
            //SearchItems is of type <DbQuery>, as of EF Core 2.1 can be used to map to non-entity types
            //What does that mean? It means I can build an arbitrary class (searchitem) and map results to it
            //The last piece of the puzzles is the mapping between column names and class fields
            //check the DATABASE VIEWS for a view of the same name as the DbQuery variable (SearchItems)


            var rawdata =
                db.SearchItems
                .Where(si =>
                    EF.Functions.Like(si.SearchTitle, "%" + searchkey + "%")
                    ||EF.Functions.Like("%"+searchkey+"%", si.SearchTitle)
                    || EF.Functions.Like(si.SearchContent, "%" + searchkey + "%")
                    || EF.Functions.Like("%" + searchkey + "%", si.SearchContent))
                .ToList();



            return View(rawdata);
            
        }

    }
}

http5204-FirstMVC/Views/Search/Explore.cshtml
@{
    ViewBag.Title = "Explore";
}

<h2>Explore</h2>

<form action="/Search/Results" method="POST" id="searchform">
    <div id="searchwrap">
        <input type="text" name="searchkey" id="searchkey" />
        <i onclick="document.getElementById('searchform').submit();" class="fas fa-search" id="search-mg"></i>
    </div>
    <input type="submit" value="submit"  style="visibility:hidden;"/>
</form>

http5204-FirstMVC/Views/Search/Results.cshtml
@model IEnumerable<http5204_FirstMVC.Models.SearchItem>

<h2>Search Results</h2>
@Html.ActionLink("Back To Search", "Explore", "Search")
@foreach(var searchitem in Model)
{
   
    <div class="searchitem">
        <h2>@Html.ActionLink(searchitem.SearchTitle,"Show/"+searchitem.SearchID,searchitem.SearchType)</h2>
        <span>Record Type: @searchitem.SearchType</span>
        <p>@searchitem.SearchContent</p>
    </div>

}