http5204-FirstMVC/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Data.SqlClient;
using System.Net;
using System.Web;
using System.Web.Mvc;
using http5204_FirstMVC.Models;
using System.Diagnostics;
using System.IO;

namespace http5204_FirstMVC.Controllers
{
    public class AuthorController : Controller
    {
        private BlogCMSContext db = new BlogCMSContext();
        
        // GET: Authors
        public ActionResult Index()
        {
            
            return View(db.Authors.ToList());
        }

        public ActionResult Show(int id)
        {
            //wrapper
            return RedirectToAction("Details/"+id);
        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Include(a=>a.Blogs).SingleOrDefault(a=>a.AuthorID==id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AuthorID,AuthorFName,AuthorLName,AuthorPenName")] Author author)
        {
            
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: Authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AuthorID,AuthorFName,AuthorLName,AuthorPenName")] Author author, HttpPostedFileBase authorimg)
        {
            //default to false (no pic)
            author.HasPic = 0;

            if (authorimg != null)
            {
                if (authorimg.ContentLength > 0)
                {
                    //file extensioncheck taken from https://www.c-sharpcorner.com/article/file-upload-extension-validation-in-asp-net-mvc-and-javascript/
                    var valtypes = new[] { "jpeg", "jpg", "png", "gif" };
                    var extension = Path.GetExtension(authorimg.FileName).Substring(1);

                    if (valtypes.Contains(extension))
                    {

                        //generic .img extension, web translates easily.
                        string fn = author.AuthorID + "." + extension;

                        //get a direct file path to imgs/authors/
                        string path = Path.Combine(Server.MapPath("~/imgs/authors"), fn);

                        //save the file
                        authorimg.SaveAs(path);

                        //let the model know that there is a picture with an extension
                        author.HasPic = 1;
                        author.ImgType = extension;

                    }
                }
            }
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

http5204-FirstMVC/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Net;
using System.Web;
using System.Web.Mvc;
using http5204_FirstMVC.Models;
//including this for the extra definition
using http5204_FirstMVC.Models.ViewModels;
using System.Diagnostics;

namespace http5204_FirstMVC.Controllers
{
    public class TagController : Controller
    {
        BlogCMSContext db = new BlogCMSContext();
        // GET: Tag
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            /*
            Alternate
            IEnumerable<Tag> tags = db.Tags.ToList();
            */

            string query = "select * from Tags";
            IEnumerable<Tag> tags = db.Tags.FromSql(query);
            
            return View(tags);
        }

        public ActionResult New()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Create(string TagName_New, string TagColor_New)
        {
            string query = "insert into tags (TagName, TagColor)" +
                " values (@name, @color)";
            SqlParameter[] myparams = new SqlParameter[2];
            myparams[0] = new SqlParameter("@name", TagName_New);
            myparams[1] = new SqlParameter("@color", TagColor_New);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }

        //TODO: EDIT VIEW, EDIT, DELETE, SHOW

        public ActionResult Edit(int? id)
        {
            if ((id == null) || (db.Tags.Find(id) == null))
            {
                return HttpNotFound();
            }
            string query = "select * from Tags where tagid=@id";
            SqlParameter param = new SqlParameter("@id",id);
            Tag mytag = db.Tags.FromSql(query, param).FirstOrDefault();
            return View(mytag);
        }

        [HttpPost]
        public ActionResult Edit(int? id, string TagName, string TagColor)
        {
            if ((id == null) || (db.Tags.Find(id) == null)){
                return HttpNotFound();
            }
            string query = "update tags set TagName=@name, TagColor=@color" +
                " where tagid=@id";
            SqlParameter[] myparams = new SqlParameter[3];
            myparams[0] = new SqlParameter("@name",TagName);
            myparams[1] = new SqlParameter("@color",TagColor);
            myparams[2] = new SqlParameter("@id", id);

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Show/" + id);
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if ((id==null)||(db.Tags.Find(id)==null))
            {
                return HttpNotFound();

            }
            string query = "delete from tags where tagid=@id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query,param);
            return View("List");
        }

        public ActionResult Show(int? id)
        {
            if ((id == null) || (db.Tags.Find(id) == null))
            {
                return HttpNotFound();

            }
            string query = "select * from Tags where tagid=@id";
            SqlParameter param = new SqlParameter("@id",id);

            Tag tagtoshow = db.Tags.Include(t=>t.pagesxtags).ThenInclude(pxt=>pxt.Page).SingleOrDefault(t=>t.TagID==id);

            return View(tagtoshow);

        }
    }
}

http5204-FirstMVC/Views/Page/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

http5204-FirstMVC/Views/Page/Edit.cshtml
@model http5204_FirstMVC.Models.ViewModels.PageEdit
@{
    ViewBag.Title = "Edit";
}

<h2>Edit @Model.Page.PageTitle</h2>

<form method="POST" action="/Page/Edit/@Model.Page.PageID">
    <div class="inprow">
        <label class="inplabel">Title</label>
        <input type="text" value="@Model.Page.PageTitle" id="PageTitle" name="PageTitle" />
    </div>
    <div class="inprow">
        <div class="inplabel">Blog</div>
        <select id="PageBlog" name="PageBlog">
            @foreach(var Blog in Model.Blogs)
            {
                string current = "";
                if (Blog.BlogID == Model.Page.Blog.BlogID)
                {
                    current = "selected";
                }
                
                <option value="@Blog.BlogID" @current>@Blog.BlogTitle</option>
            }

        </select>
    </div>
    <div class="inprow" id="colortags">
        <div class="inplabel">Page Tags:</div>
        @foreach (var Tag in Model.Tags)
        { //Loops through all tags in the database
            string selected = "";
            string neg_selected = "checked";
            //Check to see if any of these tags are applied to this page
            if (Model.Page.pagesxtags.Exists(pxt=>pxt.Tag==Tag))
            {
                selected = "checked";
                neg_selected = "";
                //html attribute on a checkbox for default check
            }
            <label>
                
                <input type="checkbox"
                       name="PageTags"
                       value="@Tag.TagID" 
                       @selected
                       onchange="var val = (this.checked) ? false : true; document.getElementById('Removed_PageTag_'+@Tag.TagID).checked=val;"/>
                @Tag.TagName
            </label>

            <!-- The natural HTML checkbox interface is a little skimpy
                so here's a bit
                of a clever trick for REMOVING tags from pages.
                build a "negative" checkbox list, so that when items are unchecked,
                we send a second list of items to remove.
                comment out the display:none; to see visually of how it works
                -->
            <label style="display:none;">
                @Tag.TagName
                <input 
                       type="checkbox" 
                       name="Removed_PageTags" 
                       id="Removed_PageTag_@Tag.TagID" 
                       value="@Tag.TagID"
                       @neg_selected/>
            </label>
        }
    </div>
    <div class="inprow">
        <div class="inplabel">Content</div>
        <textarea id="PageContent" name="PageContent">@Model.Page.PageContent</textarea>
    </div>
    <div class="inprow">
        <input type="submit" value="Submit" />
    </div>
</form>

http5204-FirstMVC/Views/Page/List.cshtml
@model IEnumerable<http5204_FirstMVC.Models.Page>
@{


    ViewBag.Title = "List";
}

<div class="banner" id="pagebanner">
    <h2>Pages</h2>
</div>
<div class="recadd">
    @Html.ActionLink("Make a New Page", "New")
</div>
<div class="reccontainer">
@foreach (var Page in Model)
{

    <div class="rec">
        
        <div class="recprofile">
            <div class="img-container">
                @if (Page.Blog.Author.HasPic == 1)
                {
                    <img src="~/imgs/authors/@(Page.Blog.Author.AuthorID).@(Page.Blog.Author.ImgType)" />
                }
                else
                {
                    <img src="~/imgs/authors/default.jpg" />
                }
            </div>
            <span class="img-caption">@Page.Blog.Author.AuthorPenName</span>
        </div>
        <div class="recbody">
            <label>@Html.ActionLink(Page.PageTitle, "Show/" + Page.PageID)</label>
            <div>
                @foreach (var pxt in Page.pagesxtags)
                {
                    <span style="background:#@pxt.Tag.TagColor; margin-bottom:5px;" class="colorbox">@Html.ActionLink(pxt.Tag.TagName, "Show/"+pxt.Tag.TagID, "Tag")</span>

                }
            </div>
            <p>@Page.PageContent</p>
            <span class="del">
                <a href="@Url.Action("Delete/"+Page.PageID)"><i class="far fa-trash-alt"></i></a>
            </span>
        </div>
        <div class="clearfix"></div>
    </div>
    
}
</div>

http5204-FirstMVC/Views/Page/New.cshtml
@model IEnumerable<http5204_FirstMVC.Models.Blog>
@{
    ViewBag.Title = "New";
}

<h2>New Page</h2>
<form method="POST" action="/Page/Create">
    <div class="inprow">
        <label class="inplabel">Title</label>
        <input id="PageTitle_New" name="PageTitle_New" />
    </div>
    <div class="inptrow">
        <label class="inplabel">Blog</label>
        <select id="PageBlog_New" name="PageBlog_New">
            @foreach (var blog in Model)
            {
                <option value="@blog.BlogID">@blog.BlogTitle</option>
            }
        </select>
    </div>
    <div class="inprow">
        <div class="inplabel">Content</div>
        <textarea  id="PageContent_New" name="PageContent_New"></textarea>
    </div>
    <div class="inprow">
        <input type="submit" value="Submit"/>
    </div>
</form>

http5204-FirstMVC/Views/Page/Show.cshtml
@model http5204_FirstMVC.Models.Page
@{
    ViewBag.Title = "Show";
}

<h2>@Model.PageTitle</h2>
@foreach(var pxt in Model.pagesxtags)
{
    <span style="background:#@pxt.Tag.TagColor" class="colorbox">@Html.ActionLink(pxt.Tag.TagName, "Show/" + pxt.Tag.TagID, "Tag")</span>

}
<div class="promptlink">
    @Html.ActionLink("Edit", "Edit/" + Model.PageID)
</div>
<div>
    <div class="pagecolumn">
        <article class="pagecontent">
            <p>@Model.PageContent</p>
        </article>
    </div>
    <div class="authorcolumn">
        <aside class="img-container">
            @{
                string imgpath = "";
            }
            @if (Model.Blog.Author.HasPic == 1)
            {
                <img src="~/imgs/authors/@(Model.Blog.Author.AuthorID).@(Model.Blog.Author.ImgType)" />
            }
            else
            {
                <img src="~/imgs/authors/default.jpg" />
            }
            
        </aside>
        <span>Written By: @Html.ActionLink(Model.Blog.Author.AuthorPenName,"Details/"+Model.Blog.Author.AuthorID,"Author")</span>
    </div>
    <div class="clearfix"></div>
</div>