http5204-FirstMVC/Models/Author.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
//using System.Data.Entity;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace http5204_FirstMVC.Models
{
    public class Author
    {
        [Key]
        public int AuthorID { get; set; }

        [Required, StringLength(255), Display(Name = "First Name")]
        public string AuthorFName { get; set; }

        [Required, StringLength(255), Display(Name = "Last Name")]
        public string AuthorLName { get; set; }

        [Required, StringLength(255), Display(Name = "Pen Name")]
        public string AuthorPenName { get; set; }

        //profile picture
        //1=>picture exists (in imgs/authors/{id}.img)
        //0=>picture doesn't exist
        public int HasPic { get; set; }

        //Accepted image formats (jpg/jpeg/png/gif)
        public string ImgType { get; set; }

        //This is how we can represent a one (author) to many (Blogs) relation
        //notice how if we were using a relational database this column
        //would be included as a foreign of authorid in pages.
        [InverseProperty("Author")]
        public List<Blog> Blogs { get; set; }


    }

    
}

http5204-FirstMVC/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Data.SqlClient;
using System.Net;
using System.Web;
using System.Web.Mvc;
using http5204_FirstMVC.Models;
using System.Diagnostics;
using System.IO;

namespace http5204_FirstMVC.Controllers
{
    public class AuthorController : Controller
    {
        private BlogCMSContext db = new BlogCMSContext();
        
        // GET: Authors
        public ActionResult Index()
        {
            
            return View(db.Authors.ToList());
        }

        public ActionResult Show(int id)
        {
            //wrapper
            return RedirectToAction("Details/"+id);
        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Include(a=>a.Blogs).SingleOrDefault(a=>a.AuthorID==id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AuthorID,AuthorFName,AuthorLName,AuthorPenName")] Author author)
        {
            
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        // GET: Authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AuthorID,AuthorFName,AuthorLName,AuthorPenName")] Author author, HttpPostedFileBase authorimg)
        {
            //default to false (no pic)
            author.HasPic = 0;

            if (authorimg != null)
            {
                if (authorimg.ContentLength > 0)
                {
                    //file extensioncheck taken from https://www.c-sharpcorner.com/article/file-upload-extension-validation-in-asp-net-mvc-and-javascript/
                    var valtypes = new[] { "jpeg", "jpg", "png", "gif" };
                    var extension = Path.GetExtension(authorimg.FileName).Substring(1);

                    if (valtypes.Contains(extension))
                    {

                        //generic .img extension, web translates easily.
                        string fn = author.AuthorID + "." + extension;

                        //get a direct file path to imgs/authors/
                        string path = Path.Combine(Server.MapPath("~/imgs/authors"), fn);

                        //save the file
                        authorimg.SaveAs(path);

                        //let the model know that there is a picture with an extension
                        author.HasPic = 1;
                        author.ImgType = extension;

                    }
                }
            }
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

http5204-FirstMVC/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System.Net;
using System.Web;
using System.Web.Mvc;
using http5204_FirstMVC.Models;
//including this for the extra definition
using http5204_FirstMVC.Models.ViewModels;
using System.Diagnostics;

namespace http5204_FirstMVC.Controllers
{
    public class BlogController : Controller
    {
        private BlogCMSContext db = new BlogCMSContext();

        /*
           Reading links to fully understand this file
           -------------------------------------------



        */


        
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            //DATA NEEDED: All Blogs in DB
            //However, we also have to include the info for the author on each blog

            //[List<Blog> blogs]=> variable named blogs which is a list of Blog
            //[.Include(b=>b.Author)]=> Get the blog's associated author
            //[.ToList()]=>Return a list of information
            List<Blog> blogs = db.Blogs.Include(b=>b.Author).ToList();

            //GOTO Views/Blog/List.cshtml
            return View(blogs);
        }

        public ActionResult New()
        {
            //DATA NEEDED
            //We only need a list of authors to populate the dropdownlist

            //Model defined in Models/ViewModels/BlogEdit.cs
            BlogEdit blogeditview = new BlogEdit();

            //[blogeditview.authors]=> Set the author field of the BlogEdit Object
            //[db.Authors.ToList()]=> Get all authors from DB
            blogeditview.Authors = db.Authors.ToList();

            //GOTO Views/Blog/New.cshtml
            return View(blogeditview);
        }

        [HttpPost]
        public ActionResult Create(string BlogTitle_New, int BlogAuthor_New, string BlogBio_New)
        {
            //Data Needed: None

            //Raw Query   
            string query = "insert into blogs (BlogTitle, BlogBio, AuthorID) values (@title, @bio, @author)";

            //SQL parameterized query technique
            //[SqlParameter[] myparams] => SET variable myparams as an array of type (SqlParameter)
            //[new SqlParameter[1]] => Create a new SqlParameter array with 3 items
            SqlParameter[] myparams = new SqlParameter[3];
            //@title paramter
            myparams[0] = new SqlParameter("@title", BlogTitle_New);
            //@bio parameter
            myparams[1] = new SqlParameter("@bio", BlogBio_New);
            //@author (id) FOREIGN KEY paramter
            myparams[2] = new SqlParameter("@author", BlogAuthor_New);
            
            //Run the parameterized query (DML - Data Manipulation Language)
            //Insert into blogs ( .. ) values ( .. ) 
            db.Database.ExecuteSqlCommand(query, myparams);

            //GOTO: 
            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            //Data Needed:
            //One particular blog (we have the id)
            //That blogs' author
            //All other authors in DB (for dropdownlist)

            //Model defined in Models/ViewModels/BlogEdit.cs
            BlogEdit blogeditview = new BlogEdit();

            //[blogeditview.authors]=>SET authors field of BlogEdit Object
            //[ db.Authors.ToList()]=>GET authors from DB into List
            blogeditview.Authors = db.Authors.ToList(); //Finds all the authors

            //[blogeditview.blog]=>SET blog field of BlogEdit Object
            //[db.Blogs]=> GET blogs from DB
            //[.Include(b => b.Author)]=> JOIN that blogs author
            //[.SingleOrDefault(b=>b.BlogID==id)]=> WHERE blogid = id
            blogeditview.Blog = db.Blogs.Include(b => b.Author).SingleOrDefault(b=>b.BlogID==id); //finds all the blogs

            //GOTO: Views/Blog/Edit.cshtml
            return View(blogeditview);
        }

        [HttpPost]
        public ActionResult Edit(int id,string BlogTitle, int BlogAuthor, string BlogBio)
        {
            //[(id == null)] => No ID passed to GET (ie. Blog/Edit) instead of (Blog/Edit/3)
            //[||]=> OR logical operator
            //[(db.Blogs.Find(id) == null)] => No blog found in DB
            if ((id == null) || (db.Blogs.Find(id) == null))
            {
                return HttpNotFound();

            }
            //Raw Update MSSQL query
            string query = "update blogs set BlogTitle=@title, BlogBio=@bio, AuthorID=@author where blogid=@id";

            //[SqlParameter[] myparams] => SET variable myparams as an array of type (SqlParameter)
            //[new SqlParameter[1]] => Create a new SqlParameter array with 4 items
            SqlParameter[] myparams = new SqlParameter[4];
            //Parameter for @title "blogtitle"
            myparams[0] = new SqlParameter("@title", BlogTitle);
            //Parameter for @bio "blogbio"
            myparams[1] = new SqlParameter("@bio", BlogBio);
            //Parameter for (author) id FOREIGN KEY
            myparams[2] = new SqlParameter("@author", BlogAuthor);
            //Pararameter for (blog) id PRIMARY KEY
            myparams[3] = new SqlParameter("@id", id);
            
            //Execute the custom SQL command with parameters
            db.Database.ExecuteSqlCommand(query, myparams);

            //GOTO: View/Blog/Show.cshtml with paramter Blogid passed
            return RedirectToAction("Show/"+id);
        }

        public ActionResult Show(int? id)
        {
            //[(id == null)] => No ID passed to GET (ie. Blog/Edit) instead of (Blog/Edit/3)
            //[||]=> OR logical operator
            //[(db.Blogs.Find(id) == null)] => No blog found in DB
            if ((id == null) || (db.Blogs.Find(id)==null))
            {
                return HttpNotFound();

            }
            //Raw MSSQL query
            string query = "select * from blogs where blogid=@id";

            //[SqlParameter[] myparams] => SET variable myparams as an array of type (SqlParameter)
            //[new SqlParameter[1]] => Create a new SqlParameter array with 1 item
            SqlParameter[] myparams = new SqlParameter[1];
            myparams[0] = new SqlParameter("@id", id);

            //Hey view.. here's a list of all the blogs in my db
            //include the pages I need
            //include the author (so I can see who wrote it)
            Blog myblog = db.Blogs.FromSql(query, myparams).Include(b=>b.Author).Include(b=>b.Pages).FirstOrDefault();

            return View(myblog);
        }
        
        public ActionResult Delete(int? id)
        {
            //[(id == null)] => No ID passed to GET (ie. Blog/Edit) instead of (Blog/Edit/3)
            //[||]=> OR logical operator
            //[(db.Blogs.Find(id) == null)] => No blog found in DB
            if ((id == null) || (db.Blogs.Find(id) == null))
            {
                return HttpNotFound();

            }
            //These three statements should definitely be wrapped in
            //a stored procedure instead of me manually doing it
            //key term here "referential integrity"

            //delete pagesxtags associated with pages associated with blogs
            string query = "delete from PagesxTags where PageID in (select PageID from pages where BlogID=@id)";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);

            //then delete associated pages
            query = "delete from pages where BlogID=@id";
            param = new SqlParameter("@id",id);
            db.Database.ExecuteSqlCommand(query,param);
            
            //finally delete blog
            query = "delete from Blogs where blogid=@id";
            param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
            return RedirectToAction("List");
        }

    }
}

http5204-FirstMVC/Views/Author/Create.cshtml
@model http5204_FirstMVC.Models.Author

@{
    ViewBag.Title = "Create";
}

<h2>Create Author</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AuthorFName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorFName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorFName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorLName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorLName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorLName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorPenName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorPenName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorPenName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

http5204-FirstMVC/Views/Author/Delete.cshtml
@model http5204_FirstMVC.Models.Author

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Author</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AuthorFName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorFName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorLName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorLName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AuthorPenName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorPenName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

http5204-FirstMVC/Views/Author/Details.cshtml
@model http5204_FirstMVC.Models.Author

@{
    ViewBag.Title = "Details";
}
<div class="promptlink">
    @Html.ActionLink("Edit", "Edit", new { id = Model.AuthorID })
</div>
<div class="promptlinkleft">
    @Html.ActionLink("Back to List", "Index")
</div>
<div>
    <div class="authoraltar">
        <div class="img-container">
            @if (Model.HasPic == 1)
            {

                <div class="img-container">
                    <img src="~/imgs/authors/@(Model.AuthorID).@(Model.ImgType)" />
                </div>
            }
            else
            {
                <img src="~/imgs/authors/default.jpg" />
            }
        </div>
        <h2>@Model.AuthorFName  @Model.AuthorLName (a.k.a) @Model.AuthorPenName</h2>
    </div>
   
    <h4>Works done by @Model.AuthorPenName</h4>
    @if (Model.Blogs != null)
    {
        <div class="inprow">
            @foreach (var blog in Model.Blogs)
            {
                <div class="recitem">
                    @Html.ActionLink(blog.BlogTitle, "Show/" + blog.BlogID, "Blog")
                </div>
            }
        </div>
    }
    else
    {
        <span style="font-style:italic;">You don't have any blogs yet.</span>
    }
    @Html.ActionLink("Create a Blog!","New","Blog")
</div>

http5204-FirstMVC/Views/Author/Edit.cshtml
@model http5204_FirstMVC.Models.Author

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Author", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <!--Don't forget this one-->
        @Html.HiddenFor(model => model.AuthorID)
        <div class="form-group">
            @Html.LabelFor(model => model.AuthorFName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorFName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorFName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorLName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorLName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorLName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorPenName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorPenName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorPenName, "", new { @class = "text-danger" })
            </div>
        </div>

        <!-- editor for a true/false value would just be a checkbox. -->
        <div class="form-group">
            <label>Current Picture:</label>
            @if (Model.HasPic == 1)
            {
                
                <div class="img-container">
                    <img src="~/imgs/authors/@(Model.AuthorID).@(Model.ImgType)" />
                </div>
            }
            else
            {
                <span>None</span>
            }
        </div>
        <div class="form-group">
            <label>Profile Picture:</label>

            <input type="file" name="authorimg" id="authorimg" />

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

http5204-FirstMVC/Views/Author/Index.cshtml
@model IEnumerable<http5204_FirstMVC.Models.Author>

@{
    ViewBag.Title = "Index";
}
<div class="banner" id="authorbanner">
    <h2>Authors</h2>
</div>
<div class="recadd">
    @Html.ActionLink("Join Us!", "Create")
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AuthorFName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AuthorLName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AuthorPenName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AuthorFName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AuthorLName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AuthorPenName)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AuthorID }) |
            @Html.ActionLink("Details", "Details", new { id=item.AuthorID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AuthorID })
        </td>
    </tr>
}

</table>